export const CREATE_CREDENTIALS = "CREATE_CREDENTIALS";
export const RETRIEVE_CREDENTIALS = "RETRIEVE_CREDENTIALS";
export const UPDATE_CREDENTIALS = "UPDATE_CREDENTIALS";
export const DELETE_CREDENTIALS = "DELETE_CREDENTIALS";
export const DELETE_ALL_CREDENTIALS = "DELETE_ALL_CREDENTIALS";